import math
import pandas as pd


def tma(df: pd.DataFrame, parameters: dict = None, columns: dict = None) -> tuple:
    """
    Calculates the Triangular Moving Average (TMA) of a series.
    TMA is generated by applying two successive simple moving averages. This
    produces a smoother curve with a triangular weighting, reducing short-term
    noise while keeping overall trend direction visible.

    Args:
        df (pd.DataFrame): The input DataFrame.
        parameters (dict, optional): Dictionary containing calculation parameters:
            - window (int): The lookback period for the TMA. Default is 20.
        columns (dict, optional): Dictionary containing column name mappings:
            - close_col (str): The column name for closing prices. Default is 'Close'.

    Returns:
        tuple: A tuple containing the TMA series and a list of column names.

    The Triangular Moving Average is calculated as follows:

    1. Determine Window Lengths:
       If window is even: Half1 = window/2, Half2 = window/2 + 1
       If window is odd: Half1 = ceil(window/2), Half2 = ceil(window/2)

    2. Calculate First Pass SMA:
       SMA1 = SMA(Close, Half1)

    3. Calculate Second Pass SMA (TMA):
       TMA = SMA(SMA1, Half2)

    Interpretation:
    - TMA places the majority of weight on the middle data points of the series.
    - It is very smooth but has significant lag (roughly twice that of an SMA).

    Use Cases:
    - Trend Identification: Excellent for visualizing the very long-term trend.
    - Noise Reduction: Filters out almost all short-term volatility.
    """
    if parameters is None:
        parameters = {}
    if columns is None:
        columns = {}

    close_col = columns.get('close_col', 'Close')
    window = int(parameters.get('window', 20))

    first_window = max(1, math.ceil(window / 2))
    second_window = max(1, math.floor(window / 2) if window % 2 == 0 else first_window)

    series = df[close_col]
    first_pass = series.rolling(window=first_window).mean()
    tma_series = first_pass.rolling(window=second_window).mean()
    tma_series.name = f'TMA_{window}'

    return tma_series, [tma_series.name]
