import math
import pandas as pd


def tma(df: pd.DataFrame, parameters: dict = None, columns: dict = None) -> tuple:
    """
    Calculates the Triangular Moving Average (TMA) of a series.

    TMA is generated by applying two successive simple moving averages. This
    produces a smoother curve with a triangular weighting, reducing short-term
    noise while keeping overall trend direction visible.
    """
    if parameters is None:
        parameters = {}
    if columns is None:
        columns = {}

    close_col = columns.get('close_col', 'Close')
    window = int(parameters.get('window', 20))

    first_window = max(1, math.ceil(window / 2))
    second_window = max(1, math.floor(window / 2) if window % 2 == 0 else first_window)

    series = df[close_col]
    first_pass = series.rolling(window=first_window).mean()
    tma_series = first_pass.rolling(window=second_window).mean()
    tma_series.name = f'TMA_{window}'

    return tma_series, [tma_series.name]
